# Generated by Django 6.0.3 on 2026-03-26 10:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('metric_label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('numeric', 'Numeric'), ('percentage', 'Percentage'), ('boolean', 'Boolean'), ('currency', 'Currency')], default='numeric', max_length=15)),
                ('start_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('target_value', models.DecimalField(decimal_places=4, default=100, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('due_date', models.DateField()),
                ('weightage', models.IntegerField(default=0, help_text='Integer % weight toward parent Objective (all KRs must sum to 100)')),
                ('rag_status', models.CharField(choices=[('not_started', 'Not Started'), ('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='not_started', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_owned_key_results', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_key_results', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_key_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'key_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyResultHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('new_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('previous_rag_status', models.CharField(choices=[('not_started', 'Not Started'), ('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=15)),
                ('new_rag_status', models.CharField(choices=[('not_started', 'Not Started'), ('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=15)),
                ('note', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='okr.keyresult')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kr_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'key_result_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('due_date', models.DateField()),
                ('quarter', models.CharField(blank=True, default='', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_objectives', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='organizations.organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_objectives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'objectives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='okr.objective'),
        ),
    ]
